### PR TITLE
Add ability to show/hide line-number independently from authorship

### PR DESCRIPTION
**Pull request by seballot**
Works from etherpad 1.8.4 (if you want to test now you get pull etherpad from https://github.com/seballot/etherpad-lite/tree/ui)

author_neat

### CODE REVIEW

**Comment by seballot** [comment]
@FramaJosephK You might be interested on this PR

**Comment by seballot** [comment]
@clkao Are you till maintaining this repo? @JohnMcLear you may be have maintainer access here?

**Comment by JohnMcLear** [comment]
I do @seballot at least for the repo, not sure for the npm module :)  You want me to give you maintainer too?

**Comment by seballot** [comment]
Great thanks for the merge !

No I do not maintainer access. I hope you will have access on npm :)

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by JohnMcLear** [comment]
I can't publish because it is weird.
```
    "prepublish": "./node_modules/.bin/lsc -cj package.ls &&\n./node_modules/.bin/lsc -bc -o static/js src/js"
```
I will look into it..  this is why people should not use fancy compilers etc. that are popular for like 2 months :P

**Comment by seballot** [comment]
maybe we can drop less script? :) and just keep the standard js files

**Comment by JohnMcLear** [comment]
+1

**Comment by seballot** [comment]
ok done and pushed

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by JohnMcLear** [comment]
Balls..

```
jose@server:~/ep_author_neat$ npm publish
npm notice
npm notice 📦  ep_author_neat@0.0.33
npm notice === Tarball Contents ===
npm notice 9.3kB   static/js/index.js
npm notice 244B    .shipit.json
npm notice 445B    ep.json
npm notice 553B    package.json
npm notice 61B     History.md
npm notice 321B    README.md
npm notice 163.1kB thumbnail.png
npm notice === Tarball Details ===
npm notice name:          ep_author_neat
npm notice version:       0.0.33
npm notice package size:  166.8 kB
npm notice unpacked size: 174.0 kB
npm notice shasum:        612d78c85748f9b74f228a1ca9f1877bc0793cd4
npm notice integrity:     sha512-UbKfdwDLA2SYn[...]a/CcozqS8wh1Q==
npm notice total files:   7
npm notice
npm ERR! code E403
npm ERR! 403 403 Forbidden - PUT https://registry.npmjs.org/ep_author_neat - You do not have permission to publish "ep_author_neat". Are you logged in as the correct user?
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jose/.npm/_logs/2020-05-06T12_37_19_939Z-debug.log
jose@server:~/ep_author_neat$

```

**Comment by JohnMcLear** [comment]
I bumped clkao for write access.  wait 24 hours

**Comment by seballot** [comment]
nice thanks !

**Comment by seballot** [comment]
@JohnMcLear any news? we would need to publish this package when publishing 1.8.4

**Comment by JohnMcLear** [comment]
No response to @clkao  ;(   I bumped again yesterday...  They are busy doing gov stuff, if this module is updated on npmjs a few days after core that's fine...

**Comment by seballot** [comment]
still nothing ? :)

**Comment by JohnMcLear** [comment]
Still nothing from @clkao 

I suggest we publish ``ep_author_neat2`` if we don't get a response by the 5th of June, sound fair?

**Comment by seballot** [comment]
ok!

**Pull request merged**
